### ISSUE TITLE
没有找到CBAM和ECA Block

### ISSUE THREAD

**Issue by x2ss** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#11]
您好，我没发现CBAM Block, ECA Block，不知道作者能否指点我一下，谢谢！

**Comment by HaloTrouvaille** [comment]
之前的版本被我剔除了，如果您需要可以加微信。

**Comment by x2ss** [comment]
> 之前的版本被我剔除了，如果您需要可以加微信。

我的手机是13817058761，可以通过这个号码加到我微信，麻烦您加我一下？

**Comment by hbwslms** [comment]
> 之前的版本被我剔除了，如果您需要可以加微信。
那可以加我一个吗，17364833562，谢谢

**Comment by hbwslms** [comment]
> 之前的版本被我剔除了，如果您需要可以加微信。

我也需要，手机号是17364833562，谢谢！
