### ISSUE TITLE
where in your code CBAM and eca blocks are defined. 

### ISSUE THREAD

**Issue by zunairaR** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#16]

**Comment by lucasjinreal** [comment]
Same question here, and which where does it inserted into?

**Comment by HaloTrouvaille** [comment]
sorry for late response，please add my wechat to get former version.

**Comment by lucasjinreal** [comment]
@HaloTrouvaille what's your wechat?

**Comment by ouening** [comment]
您好，请问可以可以在该库中添加CBAM和CAE的支持吗？

**Comment by HaloTrouvaille** [comment]
wechat ： AutrefoisLethe

**Comment by Vrishabhdhwaj** [comment]
I have a similar doubt. But I cannot access WeChat. Any other way you can share these files?
