### ISSUE TITLE
Parameters for Ghostnet + YoloV3

### ISSUE THREAD

**Issue by ghost** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#17]
Hi, 
You have mentioned the number of parameters for Ghostnet + Yolov3 to be 23.49M. I wanted to confirm if it is correct or it should be 2.349M? The number of parameters seem to be too larger than the other models.

Thanks.

**Comment by HaloTrouvaille** [comment]
Because I didn't change the head of yolov3, so its size is relatively large though the backbone is small

**Comment by ghost** [comment]
Ok, Thanks.
