### ISSUE TITLE
2020.9.26 (1) Add VoVNet as the backbone. The result is excellent.

### ISSUE THREAD

**Issue by joe660** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#19]
2020.9.26
(1) Add VoVNet as the backbone. The result is excellent.

What about this version of the cfg file?  Thank you

**Comment by HaloTrouvaille** [comment]
you can add my wechat to get vovnet cfg

**Comment by rusvagzur** [comment]
@HaloTrouvaille  @joe660 Is there a way of getting this without wechat?
