### ISSUE TITLE
请问有比如加入se模块的预训练模型么？如果没有是否可以用传统结构的预训练模型，然后对se模块权重做随机初始化？

### ISSUE THREAD

**Issue by clw5180** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#2]
RT

**Comment by clw5180** [comment]
请教 @HaloTrouvaille  老哥

**Comment by HaloTrouvaille** [comment]
您好，这个预训练我没有做。如果您想要使用传统结构的预训练模型(yolov3.weights/yolov3tiny.weights)应该也是没有问题的，因为SE我一般都是插在了骨干网络结尾。但我把预训练的代码注释掉了，您可以参照原yolo代码取消注释，利用model.oy中的load_darknet_weights函数加载.weights文件。

**Comment by clw5180** [comment]
> (yolov3.weights/yolov3tiny.weights)应该也是没有问题的，因为SE我一般都是插在了骨干网络结尾。但我把预训练的代码注释掉了，您可以参照原yolo代码取消注释，利用model.oy中的load_darknet_weights函数加载.weights文件。

非常感谢！
