### ISSUE TITLE
is it better way to construct models via pytorch api directly rather than parse from cfg?

### ISSUE THREAD

**Issue by lucasjinreal** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#4]
Is it possible convert these model construction way from cfg to directly from pytorch API?

**Comment by HaloTrouvaille** [comment]
I think it is possible. For example, you can change the backbone according to pytorch API such as ResNet. Howerver, I think cfg is clearer. If you have other problems, you can add my wechat: ssswwwyyy111 to discuss.
