### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2. Got 40 and 48

### ISSUE THREAD

**Issue by GUZ-lkc2018** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#6]
Thank you for your great work.An error occurred while I was running the code.
python3  train.py --data data/oxfordhand.data --batch-size 1 --cfg cfg/yolov3-tiny-hand-se.cfg  --epochs 100   -sr --s 0.001 --img-size 640 --weights '' 
......
RuntimeError: Sizes of tensors must match except in dimension 2. Got 40 and 48
Can you give me some advice to solve this problem?

**Comment by HaloTrouvaille** [comment]
This version doesn‘t support attention mechanism. You can add my wechat ssswwwyyy111.
