### ISSUE TITLE
AssertionError: Unsupported fields ['stopbackward', 'kernel_size', 'max_delta']

### ISSUE THREAD

**Issue by lccui** [HaloTrouvaille/YOLO-Multi-Backbones-Attention#7]

**Comment by lccui** [comment]
Warning: Unrecognized Layer Type: eca
Warning: Unrecognized Layer Type: eca
Warning: Unrecognized Layer Type: eca

**Comment by HaloTrouvaille** [comment]
You can add my wechat to get last version with eca

**Comment by lccui** [comment]
。。。what is your wechat number
